adding basic examples for upcoming HiPC tutorial
habanero-rice/hclib pull request #67
Opened 2018-12-18 11:44 UTC by vivkumar

2018-12-18 16:32 UTC, srirajpaul commented
Overall looks good. Few comments.

In case we are are planning for more extensive release of HClib, can we have a more hierarchical directory structure such as /test/tutorial/hipc18/cpp/...

Also as we discussed we can use wait() instead of wait_and_get() to make it future proof when wait_and_get gets removed. 

test/tutorial/cpp/futures/graph.cpp Line 28 a->get() does not wait for Task A to finish since void futures do nothing w.r.t get(). Might want to use wait() there.

2018-12-18 19:53 UTC, agrippa requested changes
Comments are inlined. I would also support Sriraj's comment about the folder structure, and would suggest we just create a top-level tutorials/ folder with this code underneath it in a folder called hipc18

2018-12-18 19:53 UTC, agrippa commented on test/tutorial/cpp/asyncfinish/Makefile
> +include $(HCLIB_ROOT)/include/hclib.mak
Lots of questions on this makefile (and the others that mirror it):

1. Why does clean-ob/clean remove .dSYM? We shouldn't be creating any libraries, right? Or is this some mac-specific file I'm not familiar with?
2. Same question, but for *.o. Doesn't seem like we're creating object files.
3. Why do we need both clean and clean-obj? Seems like just having clean is good enough.
4. Why does 'all' trigger 'clean' and 'clean-obj'? I'd personally prefer just 'all: $(EXE)'

2018-12-18 19:53 UTC, agrippa commented on test/tutorial/cpp/asyncfinish/arraysum.cpp
> +long get_usecs ()
We already have hclib_current_time_ns() and hclib_current_time_ms(). Could you replace all timer utilities in the application code to use one of these HClib functions?

2018-12-18 19:53 UTC, agrippa commented on test/tutorial/cpp/ddt/graph.cpp
> +/*
I think if this material is intended to be used in tutorials, every file should have a descriptive comment like the one below at the top.

Not necessarily with a picture of the task graph, but at a minimum there should be a comment describing what the file implements (even for files that have a semi-descriptive filename, e.g. "fib").

2018-12-18 19:53 UTC, agrippa commented on test/tutorial/cpp/forasync/averaging.cpp
> +  // note we are not using ceil(...) as we did in async-finish version.
Can we use /* */ style comments instead of // ?

2018-12-19 18:18 UTC, agrippa commented
@vivkumar what's the status of this? If I remember correctly, the tutorial is on the 20th, which means we're cutting this very tight. It's important to keep in mind the time zone that Sriraj and I are working on, in getting reviews back to you.

2018-12-20 01:38 UTC, vivkumar commented
Apologies for delay. I am at HiPC and did not get time to look into this earlier. I just committed the updates.

2018-12-20 21:20 UTC, agrippa commented
@vivkumar some final comments, mostly this looks great!

1. Can we just move this entirely out of the test/ folder? These aren't really tests per se, so I'd rather just have a top-level tutorials/ folder (at the same level as test/) with a single hipc18 subfolder.
2. I'm not sure why but one of the tests failed (doesn't seem like this is because of something in the code?). Hopefully, all the tests will pass with the directory structure change.

2018-12-21 01:39 UTC, srirajpaul requested changes

2018-12-21 01:39 UTC, srirajpaul commented on tutorial/hipc18/cpp/futures/graph.cpp
> +      a->get();
This get() will not wait for Task A to finish. We should use wait() here. Similarly all the get() calls in this example.

2018-12-21 01:57 UTC, srirajpaul approved these changes

2018-12-21 20:29 UTC, agrippa approved these changes

2018-12-21 20:29 UTC, merged