Some new async APIs, small formatting and comments changes
habanero-rice/hclib pull request #83
Opened 2020-05-12 22:43 UTC by agrippa

2020-05-12 22:44 UTC, agrippa commented
@srirajpaul could you take a quick look at this and let me know if it looks good? most of this is formatting and comments, but there are a few new async APIs.

2020-05-16 00:33 UTC, srirajpaul requested changes

2020-05-16 00:33 UTC, srirajpaul commented on inc/hclib-async.h
> +auto async_nb_future_await(T&& lambda, std::vector<hclib_future_t *> &&futures) ->
@agrippa I think this will not allow to pass a vector variable as shown below which would require '& futures' version. Just to confirm, is that intended?

vector< hclib_future_t*> v;
..
async_nb_future_await(.., v);

2020-05-16 00:33 UTC, srirajpaul commented on modules/common/hclib-module-common.h
> +                            addr_of_head, op, next);
@agrippa Just to confirm. Using op->next was also correct. Is it so?

2020-05-16 22:52 UTC, agrippa commented on inc/hclib-async.h
> +auto async_nb_future_await(T&& lambda, std::vector<hclib_future_t *> &&futures) ->
@srirajpaul i think that's a good point, i've added a reference variant of this API as well.

2020-05-16 22:52 UTC, agrippa commented on modules/common/hclib-module-common.h
> +                            addr_of_head, op, next);
yep, it still worked. i'm just trying to be more consistent in this function so that the next item is always referred to through the next variable.

2020-05-17 00:49 UTC, srirajpaul approved these changes
Looks good. Please go ahead and merge.

2020-05-17 16:28 UTC, merged